# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: llm_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11llm_service.proto\x12\x03llm\"Y\n\x0ePredictRequest\x12\x12\n\ninput_text\x18\x01 \x01(\t\x12\x0f\n\x07\x63hat_id\x18\x02 \x01(\x05\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\x05\"%\n\x0fPredictResponse\x12\x12\n\nprediction\x18\x01 \x01(\t\"\x07\n\x05\x65mpty2\x91\x03\n\x03LLM\x12@\n\x13PredictConversation\x12\x13.llm.PredictRequest\x1a\x14.llm.PredictResponse\x12;\n\x0ePredictMessage\x12\x13.llm.PredictRequest\x1a\x14.llm.PredictResponse\x12\x37\n\nPredictRAG\x12\x13.llm.PredictRequest\x1a\x14.llm.PredictResponse\x12\x39\n\x0cPredictAgent\x12\x13.llm.PredictRequest\x1a\x14.llm.PredictResponse\x12\x34\n\x07Summary\x12\x13.llm.PredictRequest\x1a\x14.llm.PredictResponse\x12\x30\n\rGatherMessage\x12\x13.llm.PredictRequest\x1a\n.llm.empty\x12/\n\x0c\x43learHistory\x12\x13.llm.PredictRequest\x1a\n.llm.emptyb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_PREDICTREQUEST']._serialized_start = 26
    _globals['_PREDICTREQUEST']._serialized_end = 115
    _globals['_PREDICTRESPONSE']._serialized_start = 117
    _globals['_PREDICTRESPONSE']._serialized_end = 154
    _globals['_EMPTY']._serialized_start = 156
    _globals['_EMPTY']._serialized_end = 163
    _globals['_LLM']._serialized_start = 166
    _globals['_LLM']._serialized_end = 567
# @@protoc_insertion_point(module_scope)
