version: '3.5'

services:
  db:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: bot
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

  # grafana:
  #   image: grafana/grafana-enterprise
  #   container_name: grafana
  #   restart: unless-stopped
  #   ports:
  #    - '3000:3000'
  #   volumes:
  #     # - grafana-storage:/var/lib/grafana
  #     - '$PWD/data:/var/lib/grafana'


volumes:
  grafana-storage: {}
  postgres_data:
  # dbdata6:
